%% Train ConvMixer Network with Digit Dataset
%
% This example shows how to build a ConvMixer network architecture and
% train it with the digit dataset.

% Copyright 2021 The MathWorks, Inc.

[XTrain, TTrain] = digitTrain4DArrayData;
[XTest, TTest] = digitTest4DArrayData;

% Build a ConvMixer layergraph
lg = convMixerLayers( ...
    InputSize=[28 28 1], ...
    NumClasses=10, ...
    HiddenDimension=256, ...
    Depth=5, ...
    ConnectOutputLayer=true, ...
    PatchSize=1);

% Instantiate options
options = trainingOptions( "sgdm", ...
    MaxEpochs=10, ...
    Shuffle="every-epoch", ...
    ValidationData={XTest, TTest}, ...
    Plots="training-progress" );

% Train ConvMixer
net = trainNetwork(XTrain, TTrain, lg, options);
